# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test_name',
        ),
    ]
